// Every permission tag with an empty row, found by reflection.
//
// A tag with an empty row mints its root with no context, so any code
// that can name the tag can make a token of it.  That is sound only when
// a root of the tag is no authority: the tag is private to the class
// that mints it, or the token proves nothing outside the owner of the
// memory it names.  A tag whose root is an authority names an effect in
// its row, so the root mint needs a context that owns that effect.
//
// The walk reads each class of the foundation, fixy and crucible
// namespaces that this file can name, nested classes too.  It does not
// read a private nested class: only its enclosing class can name that
// tag, so only that class mints a root of it.  The build
// includes each header of include/ that declares a row
// (permission_row_headers.h, generated by test/CMakeLists.txt), so a new
// header joins the walk with no edit here.  The roster below gives the
// reason of each empty-row tag.  A tag that the walk finds and the roster
// does not name fails the build, and so does a roster entry that the walk
// does not find.
//
// The walk cannot read a class template, because a member of a template
// is known only for an instance.  The template tags with an empty row
// are the channel role tags (spsc_tag, mpsc_tag, metalog_tag) and
// perf::detail::bpf_map_region.  A root of the whole tag of a channel
// gives both endpoints of that channel, so it is an authority that this
// walk does not see.  A BPF map region is minted inside the map door.

#include "permission_row_headers.h"

#include <crucible/warden/Quarantine.h>
#include <foundation/effects/Row.h>
#include <foundation/permissions/Permission.h>

#include <cstdio>
#include <meta>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace {

namespace fp = ::foundation::permissions;
namespace fe = ::foundation::effects;

// Each class of one namespace or class, and of each namespace and class
// in it, that this file can name.  A class template, a type alias and a
// namespace alias are not read: an alias names a class that the walk
// reads where it is declared.  Complexity: linear in the count of members
// that the walk reads.
consteval void collect_classes(std::meta::info scope, std::vector<std::meta::info>& classes) {
    for (std::meta::info member : std::meta::members_of(scope, std::meta::access_context::current())) {
        if (std::meta::is_namespace(member)) {
            if (!std::meta::is_namespace_alias(member)) collect_classes(member, classes);
        } else if (std::meta::is_type(member) && !std::meta::is_type_alias(member) && std::meta::is_class_type(member)
                   && std::meta::is_complete_type(member)) {
            classes.push_back(member);
            collect_classes(member, classes);
        }
    }
}

consteval std::vector<std::meta::info> every_class() {
    std::vector<std::meta::info> classes;
    collect_classes(^^::foundation, classes);
    collect_classes(^^::fixy, classes);
    collect_classes(^^::crucible, classes);
    return classes;
}

// The qualified name of a class, with each enclosing scope.
consteval std::string qualified_name(std::meta::info named) {
    std::string name{std::meta::has_identifier(named) ? std::meta::identifier_of(named) : "(anonymous)"};
    for (std::meta::info scope = std::meta::parent_of(named); scope != ^^::; scope = std::meta::parent_of(scope)) {
        std::string outer{std::meta::has_identifier(scope) ? std::meta::identifier_of(scope) : "(anonymous)"};
        name = outer + "::" + name;
    }
    return name;
}

// A structural type, so the rows can live in a static array: the name
// points into a static string that define_static_string made.
struct TagRow {
    char const* name = nullptr;
    bool is_empty = false;
};

// Each permission tag that the walk finds: an empty class with a row.
consteval std::vector<TagRow> every_tag() {
    static constexpr auto classes = std::define_static_array(every_class());
    std::vector<TagRow> tags;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wshadow"
    template for (constexpr std::meta::info member : classes) {
        using Class = [:member:];
        if constexpr (std::is_empty_v<Class>) {
            if constexpr (fp::has_permission_row(member)) {
                tags.push_back(
                    TagRow{std::define_static_string(qualified_name(member)), fp::permission_row_empty(member)});
            }
        }
    }
#pragma GCC diagnostic pop
    return tags;
}

constexpr auto kTags = std::define_static_array(every_tag());

struct RosterEntry {
    std::string_view name;
    std::string_view reason;
};

// The reason of each tag with an empty row.
constexpr RosterEntry kEmptyRowRoster[] = {
    {"crucible::KernelCache::KernelCompileTag",
     "the token writes the slot that it is given, and the slots of a cache are private to the cache"},
    {"crucible::observe::RuntimeMetricsWriterTag",
     "the metrics channel names the brand of its writer root, so a root of another brand opens no writer"},
    {"crucible::observe::RuntimeMetricsReaderTag",
     "the metrics channel names the brand of its reader root, so a root of another brand opens no reader"},
    {"crucible::ledger::probe_detail::ProbeRegionTag",
     "a region tag of the probe map door, which mints the root, and a root maps no memory"},
    {"fixy::detail::owned_mmap_self_test::DummyTag", "a self-test tag of fixy/OwnedMmap.h"},
    {"fixy::detail::shared_region_self_test::probe_tag", "a self-test tag of fixy/SharedRegion.h"},
    {"fixy::detail::owned_region_test_tag", "a self-test tag of fixy/OwnedRegion.h"},
    {"fixy::detail::owned_region_self_test::test_tag_a", "a self-test tag of fixy/OwnedRegion.h"},
    {"fixy::detail::owned_region_self_test::test_tag_b", "a self-test tag of fixy/OwnedRegion.h"},
    {"fixy::detail::witnessed_self_test::pure_tag", "a self-test tag of fixy/Witnessed.h"},
    {"fixy::concurrent::swmr_session::detail::swmr_session_witness::WriterTag",
     "a witness tag of fixy/concurrent/SwmrSession.h"},
    {"fixy::concurrent::swmr_session::detail::swmr_session_witness::ReaderTag",
     "a witness tag of fixy/concurrent/SwmrSession.h"},
    {"foundation::permissions::detail::seplog_test_tag", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_test_left", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_test_right", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_combine_n_parent",
     "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_combine_n_a", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_combine_n_b", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::seplog_combine_n_c", "a self-test tag of foundation/permissions/Permission.h"},
    {"foundation::permissions::detail::read_view_test_tag", "a self-test tag of foundation/permissions/ReadView.h"},
};

consteval bool roster_names(std::string_view name) {
    for (RosterEntry const& entry : kEmptyRowRoster) {
        if (entry.name == name) return true;
    }
    return false;
}

// The first empty-row tag that the roster does not name, or an empty
// string when the roster names each one.
consteval std::string_view first_unclassified() {
    for (TagRow const& tag : kTags) {
        if (tag.is_empty && !roster_names(tag.name)) return std::string_view{tag.name};
    }
    return {};
}

// The first roster entry that the walk does not find as an empty-row
// tag, or an empty string when the walk finds each one.
consteval std::string_view first_stale() {
    for (RosterEntry const& entry : kEmptyRowRoster) {
        bool found = false;
        for (TagRow const& tag : kTags) {
            if (tag.is_empty && std::string_view{tag.name} == entry.name) found = true;
        }
        if (!found) return entry.name;
    }
    return {};
}

// Copies the characters one at a time.  The string constructors compare
// the source address with null, and GCC does not fold that comparison for
// an address of a static string that define_static_string made.
consteval std::string message_naming(std::string_view head, std::string_view name, std::string_view tail) {
    std::string message{head};
    for (char const letter : name) {
        message.push_back(letter);
    }
    message += tail;
    return message;
}

consteval std::string unclassified_message() {
    return message_naming("the permission tag ", first_unclassified(),
                          " has an empty row and no roster entry.  If a root of the tag is an authority, name an "
                          "effect in its row.  If it is not, add the tag and the reason to kEmptyRowRoster");
}

consteval std::string stale_message() {
    return message_naming("the roster entry ", first_stale(),
                          " names no empty-row tag that the walk finds.  Remove the entry, or give the tag its "
                          "empty row again");
}

consteval bool tag_found_with_row(std::string_view name, bool is_empty) {
    for (TagRow const& tag : kTags) {
        if (std::string_view{tag.name} == name) return tag.is_empty == is_empty;
    }
    return false;
}

// The walk is not vacuous: it finds the tags of the canonical namespace,
// which have rows that name effects.
static_assert(kTags.size() > 20, "the walk found almost no permission tag, so the roster check proves nothing");
static_assert(tag_found_with_row("foundation::permissions::tag::HugePageTag", false));
static_assert(tag_found_with_row("crucible::warden::quarantine_tag::OperatorOverride", false),
              "the operator override is an authority, so its row names an effect");
static_assert(std::is_same_v<fp::permission_row_t<crucible::warden::quarantine_tag::OperatorOverride>,
                             fe::Row<fe::Effect::Init>>);

static_assert(first_unclassified().empty(), unclassified_message());
static_assert(first_stale().empty(), stale_message());

}  // namespace

int main() {
    std::size_t empty_rows = 0;
    std::printf("test_permission_row_roster: permission tags with an empty row\n");
    for (TagRow const& tag : kTags) {
        if (!tag.is_empty) continue;
        ++empty_rows;
        std::printf("  %s\n", tag.name);
    }
    std::printf("test_permission_row_roster: %zu tags, %zu with an empty row: PASSED\n", kTags.size(), empty_rows);
    return 0;
}
