// GENERATED by scripts/check-witness-roster.py --gen from
// scripts/witness-roster.txt.  Edit the roster, not this file.
// clang-format off: the generator owns this layout, and --check compares it byte for byte.
//
// fixy::concurrent::swmr_session::SwmrSession<int, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderBrand, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterBrand>::ReaderHandle attests to a fact it cannot see.  The expression below is the
// raw data a forger would hand its constructor, and the fixture stands
// on the door staying shut: the construction must be refused, and the
// refusal must read "is private within this context".
//
// The second required diagnostic is the constructor as the compiler
// renders it, with parentheses.  The source spells it with braces, so
// the match cannot be satisfied by the fixture's own text.

#include <fixy/concurrent/SwmrSession.h>

#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <utility>

namespace forge {
// Stand-ins for values a forger would have to hand over.  Neither
// returns: the fixture is compiled, never run.
template <class T> [[gnu::noinline]] T& lvalue() noexcept { std::abort(); }
template <class T> [[gnu::noinline]] T&& rvalue() noexcept { std::abort(); }
}  // namespace forge

int main() {
    [[maybe_unused]] auto forged = fixy::concurrent::swmr_session::SwmrSession<int, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderBrand, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterBrand>::ReaderHandle{forge::lvalue<fixy::concurrent::swmr_session::SwmrSession<int, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderBrand, fixy::concurrent::swmr_session::detail::swmr_session_self_test::WriterBrand>>(), forge::rvalue<foundation::permissions::SharedPermissionGuard<fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderTag, fixy::concurrent::swmr_session::detail::swmr_session_self_test::ReaderBrand>>()};
    return 0;
}
