// GENERATED by scripts/check-witness-roster.sh --gen from
// scripts/witness-roster.txt.  Edit the roster, not this file.
//
// foundation::effects::Capability<foundation::effects::Effect::IO, foundation::effects::Bg> attests to a fact it cannot see.  The expression below is the
// raw data a forger would hand its constructor, and the fixture stands
// on the door staying shut: the construction must be refused, and the
// refusal must read "no matching function for call".
//
// The second required diagnostic is the constructor as the compiler
// renders it, with parentheses.  The source spells it with braces, so
// the match cannot be satisfied by the fixture's own text.

#include <foundation/effects/Capability.h>

#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <utility>

namespace forge {
// Stand-ins for values a forger would have to hand over.  Neither
// returns: the fixture is compiled, never run.
template <class T> [[gnu::noinline]] T& lvalue() noexcept { std::abort(); }
template <class T> [[gnu::noinline]] T&& rvalue() noexcept { std::abort(); }
}  // namespace forge

int main() {
    [[maybe_unused]] auto forged = foundation::effects::Capability<foundation::effects::Effect::IO, foundation::effects::Bg>{};
    return 0;
}
