// GENERATED by scripts/check-witness-roster.sh --gen from
// scripts/witness-roster.txt.  Edit the roster, not this file.
//
// fixy::concurrent::PipelineDag<fixy::concurrent::StageGraph<fixy::concurrent::StagePack<fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>, fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>>, fixy::concurrent::EdgePack<fixy::concurrent::StageEdge<0, 1>>>> attests to a fact it cannot see.  The expression below is the
// raw data a forger would hand its constructor, and the fixture stands
// on the door staying shut: the construction must be refused, and the
// refusal must read "is private within this context".
//
// The second required diagnostic is the constructor as the compiler
// renders it, with parentheses.  The source spells it with braces, so
// the match cannot be satisfied by the fixture's own text.

#include <fixy/concurrent/Pipeline.h>

#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <utility>

namespace forge {
// Stand-ins for values a forger would have to hand over.  Neither
// returns: the fixture is compiled, never run.
template <class T> [[gnu::noinline]] T& lvalue() noexcept { std::abort(); }
template <class T> [[gnu::noinline]] T&& rvalue() noexcept { std::abort(); }
}  // namespace forge

int main() {
    [[maybe_unused]] auto forged = fixy::concurrent::PipelineDag<fixy::concurrent::StageGraph<fixy::concurrent::StagePack<fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>, fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>>, fixy::concurrent::EdgePack<fixy::concurrent::StageEdge<0, 1>>>>{forge::rvalue<fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>>(), forge::rvalue<fixy::concurrent::Stage<&fixy::concurrent::detail::stage_self_test::stage_pass_through, fixy::HotFgCtx>>()};
    return 0;
}
