"""The golden file and the C++ tests that are emitted from it.

The golden file is a CSV table with one row per measured property.
Lines that start with ``#`` are metadata.  The columns:

    family   the relation and property, for example ``old.projection``
    case     the case identifier: a corpus letter and a number, or
             ``p_`` and the name of a paper example (see CORPORA)
    role     the role of a projection, or ``-``
    global   the global type in the compact form of model.py
    oracle   the oracle's answer: a local type, ``none``, ``true``,
             ``false`` or an execution verdict; for the fixy families,
             ``e0 || e1``
    ours     what our relation computed: ``=`` when it equals the
             oracle's answer, a canonical C++ spelling, ``true``,
             ``false``, ``reject:<tag>`` or an execution verdict
    status   ``agree``, ``divergence``, or ``gap`` for a type that our
             protocol language cannot spell
    class    for a divergence or a gap, the kind of disagreement; the
             shrinker keeps it while it shrinks a case
    note     for a divergence, which side is wrong and the definition
             that decides it

The tests assert what our relation computed.  For an agree row that is
the oracle's answer, so a change to our relation that breaks agreement
fails the build.  For a divergence row the assertion pins our current
answer, so a repair also fails the build, and the golden file must be
regenerated.  The divergence list can therefore only shrink by an
explicit step.  A row whose relation rejects with a hard error cannot
be compiled in the shared test, so it stays in the golden file only.
So do the gap rows and the rows of RECORD_FAMILIES.

Emission reads the golden file and nothing else, so the drift check in
CI needs no oracle and no compiler.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass
from pathlib import Path

from model import (cpp_fixy_global, cpp_fixy_local, cpp_fixy_peer_local, cpp_old_global,
                   cpp_old_local, cpp_prelude, cpp_role, local_of, mutations, read_global,
                   read_local, show_global)

COLUMNS = ("family", "case", "role", "global", "oracle", "ours", "status", "class", "note")

# The corpora, in the order of the golden file.  For the frozen tree: r
# random, a adversarial, h hand-written review cases, m minimal forms of
# the divergences that the shrinker found.  p holds the paper examples
# of the two trees.  fr, fa, fh and fm are the random, adversarial,
# hand-written and minimal corpora of the fixy tree.
CORPORA = ("r", "a", "h", "p", "m", "fr", "fa", "fh", "fm")

FIXY_FAMILIES = ("fixy.dual", "fixy.is_dual", "fixy.involution", "fixy.involutive_flag",
                 "fixy.well_formed", "fixy.accepts")
MULTI_FAMILIES = ("fixy.global_wf", "fixy.projection", "fixy.live")
SUBTYPE_FAMILIES = ("fixy.subtype_sync", "fixy.subtype_async")
# The capacity that the asynchronous subtyping rows use, in the probe, in
# the run that decides them, and in the emitted assertion.
SUBTYPE_CAPACITY = 3
SUBTYPE_MUTATIONS = 4
OLD_FAMILIES = ("old.projection", "old.well_formed")
# Families that no C++ test can assert: the execution verdict of the
# frozen tree's projection, and the run of the oracle's own projection.
RECORD_FAMILIES = ("old.execution", "oracle.safety")
FAMILIES = FIXY_FAMILIES + MULTI_FAMILIES + SUBTYPE_FAMILIES + OLD_FAMILIES + RECORD_FAMILIES
STATUSES = ("agree", "divergence", "gap")

GENERATED_NOTICE = (
    "// Generated by tools/session_oracle from test/session_oracle/golden.csv.\n"
    "// Do not edit.  Regenerate with scripts/session-oracle.sh --regenerate, or\n"
    "// re-emit after a note change with scripts/session-oracle.sh --emit.\n")


class GoldenError(ValueError):
    """The golden file is malformed."""


@dataclass(frozen=True, slots=True)
class Row:
    """One measured property."""

    family: str
    case: str
    role: str
    global_text: str
    oracle: str
    ours: str
    status: str
    klass: str
    note: str

    def as_list(self) -> list[str]:
        """Return the row as CSV fields in column order."""
        return [self.family, self.case, self.role, self.global_text, self.oracle,
                self.ours, self.status, self.klass, self.note]


def case_key(case: str) -> tuple[int, int, str]:
    """Return the sort key of a case identifier: corpus, number, name."""
    if case.startswith("p_") and case[2:].replace("_", "").isalnum():
        return (CORPORA.index("p"), 0, case)
    corpus = case.rstrip("0123456789")
    digits = case[len(corpus):]
    if corpus not in CORPORA or corpus == "p" or not digits:
        raise GoldenError(f"malformed case identifier {case!r}")
    return (CORPORA.index(corpus), int(digits), "")


def read_golden(path: Path) -> tuple[list[str], list[Row]]:
    """Read and validate the golden file.  Return metadata and rows.

    Every row must name a known family and status, a divergence must
    carry a note, and the global type must parse.  O(rows).
    """
    meta: list[str] = []
    body: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        (meta if line.startswith("#") else body).append(line)
    reader = csv.reader(body)
    header = next(reader, None)
    if header is None or tuple(header) != COLUMNS:
        raise GoldenError(f"{path}: the header must be {','.join(COLUMNS)}")
    rows: list[Row] = []
    for lineno, fields in enumerate(reader, start=len(meta) + 2):
        if len(fields) != len(COLUMNS):
            raise GoldenError(f"{path}:{lineno}: {len(fields)} fields, expected {len(COLUMNS)}")
        row = Row(*fields)
        case_key(row.case)
        if row.family not in FAMILIES:
            raise GoldenError(f"{path}:{lineno}: unknown family {row.family!r}")
        if row.status not in STATUSES:
            raise GoldenError(f"{path}:{lineno}: unknown status {row.status!r}")
        if row.status != "agree" and not (row.note and row.klass):
            raise GoldenError(f"{path}:{lineno}: a {row.status} must carry a class and a note")
        if row.status == "agree" and row.ours.startswith("reject:") and row.oracle != "none":
            raise GoldenError(f"{path}:{lineno}: a rejection agrees only with oracle 'none'")
        show_global(read_global(row.global_text))
        rows.append(row)
    return meta, rows


def write_golden(path: Path, meta: list[str], rows: list[Row]) -> None:
    """Write the golden file in a deterministic order."""
    ordered = sorted(rows, key=lambda r: (FAMILIES.index(r.family), case_key(r.case), r.role))
    buf = io.StringIO()
    for line in meta:
        buf.write(line + "\n")
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(COLUMNS)
    for row in ordered:
        writer.writerow(row.as_list())
    path.write_text(buf.getvalue(), encoding="utf-8")


def _pin(spelling: str) -> str:
    """Qualify a canonical spelling from the global namespace."""
    return "::" + spelling


def _message(row: Row) -> str:
    role = f" role {row.role}" if row.role != "-" else ""
    return f"session_oracle {row.family} case {row.case}{role}: {row.status}"


def _fixy_pair(row: Row) -> tuple[str, str]:
    left, _, right = row.oracle.partition(" || ")
    e0, e1 = read_local(left), read_local(right)
    if e0 is None or e1 is None:
        raise GoldenError(f"fixy case {row.case}: the oracle rejected a two-party projection")
    return cpp_fixy_local(e0), cpp_fixy_local(e1)


_FIXY_BOOL = {
    "fixy.is_dual": "fs::is_dual_v<T0, T1>",
    "fixy.involution": "std::is_same_v<fs::dual_of_t<fs::dual_of_t<T0>>, T0>",
    "fixy.involutive_flag": "fs::is_dual_involutive_v<T0>",
    "fixy.well_formed": "(fs::is_well_formed_v<T0> && fs::is_well_formed_v<T1>)",
    "fixy.accepts": ("(fs::is_well_formed_v<N0> && fs::is_well_formed_v<N1> && "
                     "fs::is_dual_v<N0, N1>)"),
}


def fixy_accepts_expression() -> str:
    """Return the C++ expression that fixy.accepts measures on N0 and N1."""
    return _FIXY_BOOL["fixy.accepts"]


def _hard_error(row: Row) -> bool:
    """Return true for a row whose relation stopped the build, which no test can assert."""
    return row.ours.startswith("reject:") and row.family not in ("old.projection",)


def _fixy_assert(row: Row) -> str:
    msg = _message(row)
    if _hard_error(row):
        return f"// {row.family}: the relation stops the build ({row.ours[7:]})\n"
    if row.family == "fixy.dual":
        target = "T1" if row.ours == "=" else _pin(row.ours)
        return f"static_assert(std::is_same_v<fs::dual_of_t<T0>, {target}>, \"{msg}\");\n"
    if row.ours not in ("true", "false"):
        raise GoldenError(f"{row.family} case {row.case}: ours must be true or false")
    return f"static_assert({_FIXY_BOOL[row.family]} == {row.ours}, \"{msg}\");\n"


def _namespace(case: str) -> str:
    return "c_" + case


def emit_fixy(rows: list[Row]) -> str:
    """Return the fixy test translation unit.  O(rows)."""
    cases: dict[str, list[Row]] = {}
    for row in rows:
        if row.family in FIXY_FAMILIES and row.status != "gap":
            cases.setdefault(row.case, []).append(row)
    out = [GENERATED_NOTICE, "//\n",
           "// Duality against the projection oracle.  For a two-party global type the\n",
           "// oracle's projection onto role 1 is the dual of its projection onto role 0,\n",
           "// so dual_of_t must map T0 onto T1.  N0 and N1 are the naive reading of the\n",
           "// global type, which fixy.accepts compares with the oracle.\n\n",
           "#include <fixy/session/Protocol.h>\n\n#include <type_traits>\n\n",
           cpp_prelude(), "\nnamespace fs = ::fixy::session;\n\n",
           "namespace session_oracle::fixy_duality {\n\n"]
    for case in sorted(cases, key=case_key):
        group = sorted(cases[case], key=lambda r: FIXY_FAMILIES.index(r.family))
        out.append(f"// {group[0].global_text}\nnamespace {_namespace(case)} {{\n")
        pair_rows = [r for r in group if r.family != "fixy.accepts"]
        if pair_rows:
            t0, t1 = _fixy_pair(pair_rows[0])
            out.append(f"using T0 = {t0};\nusing T1 = {t1};\n")
        if any(r.family == "fixy.accepts" for r in group):
            g = read_global(group[0].global_text)
            out.append(f"using N0 = {cpp_fixy_local(local_of(g, 0))};\n"
                       f"using N1 = {cpp_fixy_local(local_of(g, 1))};\n")
        for row in group:
            out.append(_fixy_assert(row))
        out.append(f"}}  // namespace {_namespace(case)}\n\n")
    out.append("}  // namespace session_oracle::fixy_duality\n\nint main() { return 0; }\n")
    return "".join(out)


def emit_old(rows: list[Row]) -> str:
    """Return the frozen-tree test translation unit.  O(rows)."""
    cases: dict[str, list[Row]] = {}
    for row in rows:
        if row.family in OLD_FAMILIES and row.status != "gap":
            cases.setdefault(row.case, []).append(row)
    out = [GENERATED_NOTICE, "//\n",
           "// Projection and well-formedness of the frozen tree against the projection\n",
           "// oracle.  A row whose projection rejects with a hard error is not asserted;\n",
           "// the golden file records it.\n\n",
           "#include <crucible/sessions/SessionGlobal.h>\n\n#include <type_traits>\n\n",
           cpp_prelude(), "\nnamespace pr = ::crucible::safety::proto;\n\n",
           "namespace session_oracle::old_projection {\n\n"]
    for case in sorted(cases, key=case_key):
        group = sorted(cases[case], key=lambda r: (OLD_FAMILIES.index(r.family), r.role))
        g = read_global(group[0].global_text)
        out.append(f"// {group[0].global_text}\nnamespace {_namespace(case)} {{\n")
        out.append(f"using G = {cpp_old_global(g)};\n")
        for row in group:
            msg = _message(row)
            if row.family == "old.well_formed":
                out.append(f"static_assert(pr::is_global_well_formed_v<G> == {row.ours}, \"{msg}\");\n")
                continue
            if row.ours.startswith("reject:"):
                out.append(f"// role {row.role}: our projection rejects ({row.ours[7:]}); "
                           f"oracle {row.oracle}\n")
                continue
            if row.ours == "=":
                expected = read_local(row.oracle)
                if expected is None:
                    raise GoldenError(f"old.projection case {row.case}: '=' needs an oracle type")
                target = cpp_old_local(expected)
            else:
                target = _pin(row.ours)
            out.append(f"static_assert(std::is_same_v<pr::project_t<G, {cpp_role(int(row.role))}>, "
                       f"{target}>, \"{msg}\");\n")
        out.append(f"}}  // namespace {_namespace(case)}\n\n")
    out.append("}  // namespace session_oracle::old_projection\n\nint main() { return 0; }\n")
    return "".join(out)


def emit_multi(rows: list[Row]) -> str:
    """Return the fixy multiparty test translation unit.  O(rows)."""
    cases: dict[str, list[Row]] = {}
    for row in rows:
        if row.family in MULTI_FAMILIES and row.status != "gap":
            cases.setdefault(row.case, []).append(row)
    out = [GENERATED_NOTICE, "//\n",
           "// Global types, projection and liveness of fixy/session against the\n",
           "// projection oracle.  A projection row asserts the oracle's answer when\n",
           "// fixy gives it as written, and pins fixy's answer otherwise.\n\n",
           "#include <fixy/session/Liveness.h>\n#include <fixy/session/Projection.h>\n\n",
           "#include <type_traits>\n\n",
           cpp_prelude(), "\nnamespace fs = ::fixy::session;\nnamespace fg = ::fixy::session::global;\n\n",
           "namespace session_oracle::fixy_projection {\n\n"]
    for case in sorted(cases, key=case_key):
        group = sorted(cases[case], key=lambda r: (MULTI_FAMILIES.index(r.family), r.role))
        g = read_global(group[0].global_text)
        out.append(f"// {group[0].global_text}\nnamespace {_namespace(case)} {{\n")
        out.append(f"using G = {cpp_fixy_global(g)};\n")
        for row in group:
            msg = _message(row)
            if _hard_error(row):
                out.append(f"// {row.family}: the relation stops the build ({row.ours[7:]})\n")
                continue
            if row.family == "fixy.global_wf":
                out.append(f"static_assert(fg::is_global_well_formed_v<G> == {row.ours}, \"{msg}\");\n")
            elif row.family == "fixy.live":
                out.append(f"static_assert(fs::is_live_by_construction_v<G> == {row.ours}, \"{msg}\");\n")
            else:
                if row.ours == "=":
                    expected = read_local(row.oracle)
                    if expected is None:
                        raise GoldenError(f"fixy.projection case {row.case}: '=' needs an oracle type")
                    target = f"fs::Projected<fs::OutQueue<>, {cpp_fixy_peer_local(expected)}>"
                else:
                    target = _pin(row.ours)
                out.append(f"static_assert(std::is_same_v<fs::project_t<G, {cpp_role(int(row.role))}>, "
                           f"{target}>, \"{msg}\");\n")
        out.append(f"}}  // namespace {_namespace(case)}\n\n")
    out.append("}  // namespace session_oracle::fixy_projection\n\nint main() { return 0; }\n")
    return "".join(out)


def subtype_pair(g_text: str, role: str) -> tuple[str, str]:
    """Return the C++ spellings of T and U for a subtyping row.

    ``role`` is ``k+name`` for the pair (mutation k of U, U) and
    ``k-name`` for the pair (U, mutation k of U), where U is the naive
    reading of the global type onto role 0 (model.local_of).
    """
    u = local_of(read_global(g_text), 0)
    sep = "+" if "+" in role else "-"
    index, _, name = role.partition(sep)
    found = mutations(u, SUBTYPE_MUTATIONS)
    k = int(index)
    if k >= len(found) or found[k][0] != name:
        raise GoldenError(f"subtype row {g_text} {role}: no mutation {name} at index {k}")
    t = found[k][1]
    first, second = (t, u) if sep == "+" else (u, t)
    return cpp_fixy_local(first), cpp_fixy_local(second)


def emit_subtype(rows: list[Row]) -> str:
    """Return the fixy subtyping test translation unit.  O(rows)."""
    cases: dict[str, list[Row]] = {}
    for row in rows:
        if row.family in SUBTYPE_FAMILIES and row.status != "gap" and not _hard_error(row):
            cases.setdefault(row.case, []).append(row)
    out = [GENERATED_NOTICE, "//\n",
           "// Subtyping of fixy/session against runs of each pair: T refines U when T runs\n",
           "// against the dual of U without a wrong message, a deadlock or a loop that never\n",
           "// acts.  Each U is the naive reading of a global type, and each T one change of U.\n\n",
           "#include <fixy/session/Subtype.h>\n\n#include <type_traits>\n\n",
           cpp_prelude(), "\nnamespace fs = ::fixy::session;\n\n",
           "namespace session_oracle::fixy_subtype {\n\n"]
    for case in sorted(cases, key=case_key):
        group = sorted(cases[case], key=lambda r: (r.role, SUBTYPE_FAMILIES.index(r.family)))
        out.append(f"// {group[0].global_text}\nnamespace {_namespace(case)} {{\n")
        seen: set[str] = set()
        for row in group:
            ns = "m" + row.role.split("+")[0].split("-")[0] + ("f" if "+" in row.role else "r")
            if ns not in seen:
                if seen:
                    out.append(f"}}  // namespace {sorted(seen)[-1]}\n")
                seen = {ns}
                t, u = subtype_pair(row.global_text, row.role)
                out.append(f"namespace {ns} {{\n// {row.role}\nusing T = {t};\nusing U = {u};\n")
            expr = ("fs::is_subtype_sync_v<T, U>" if row.family == "fixy.subtype_sync"
                    else f"fs::is_subtype_async_v<T, U, {SUBTYPE_CAPACITY}>")
            out.append(f"static_assert({expr} == {row.ours}, \"{_message(row)}\");\n")
        if seen:
            out.append(f"}}  // namespace {sorted(seen)[-1]}\n")
        out.append(f"}}  // namespace {_namespace(case)}\n\n")
    out.append("}  // namespace session_oracle::fixy_subtype\n\nint main() { return 0; }\n")
    return "".join(out)


def _split_closers(text: str) -> str:
    """Write each run of closing angle brackets as separate tokens.

    The pinned tree-sitter grammar that the AST gates use reads a long
    run such as >>>> inside a static_assert argument as shift operators.
    The emitted tests hold no shift operator, so every >> becomes > >.
    O(length).
    """
    while ">>" in text:
        text = text.replace(">>", "> >")
    return text


def emit_all(rows: list[Row]) -> dict[str, str]:
    """Return the file name and text of every emitted test."""
    return {name: _split_closers(text) for name, text in (
        ("generated_fixy_duality.cpp", emit_fixy(rows)),
        ("generated_fixy_projection.cpp", emit_multi(rows)),
        ("generated_fixy_subtype.cpp", emit_subtype(rows)),
        ("generated_old_projection.cpp", emit_old(rows)))}
