#pragma once

// Shared pieces of the boundary harnesses.
//
// Each harness takes one byte string from outside the process and drives
// one boundary where bytes become typed values.  Two outcomes count as a
// finding: a sanitizer report, and an accepted value that breaks the claim
// its type makes.  The second kind is checked with CRUCIBLE_FUZZ_CLAIM.  It
// aborts, so a fuzzer records it as a crash, the same as a sanitizer report.
//
// A harness is an inline function in a header under harnesses/.  The fuzz
// binary calls it from LLVMFuzzerTestOneInput, and the property test
// prop_boundary_harnesses calls every harness with generated bytes, so one
// body serves the coverage-guided run and the deterministic ctest run.

#include <foundation/effects/Effect.h>
#include <foundation/reflect/EnumName.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <span>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>
#include <unistd.h>

namespace crucible::fuzz::boundary {

// Stops the process when a value that crossed the boundary breaks the claim
// of its type.
[[noreturn, gnu::cold, gnu::noinline]] inline void claim_broken(const char* harness, const char* claim) noexcept {
    std::fprintf(stderr, "fuzz %s: an accepted value breaks its claim: %s\n", harness, claim);
    std::abort();
}

#define CRUCIBLE_FUZZ_CLAIM(harness, cond)                                        \
    do {                                                                         \
        if (!(cond)) [[unlikely]]                                                \
            ::crucible::fuzz::boundary::claim_broken(harness, #cond);            \
    } while (0)

// Splits one fuzz input into fields.  A read past the end yields zero bytes
// for the missing part, so every input of every length is a valid program
// of reads.
class ByteCursor {
public:
    explicit constexpr ByteCursor(std::span<const std::uint8_t> bytes) noexcept : bytes_{bytes} {}

    template <typename T>
        requires std::is_integral_v<T> || std::is_enum_v<T>
    [[nodiscard]] T take() noexcept {
        T value{};
        const std::size_t n = std::min(sizeof(T), bytes_.size());
        if (n > 0) std::memcpy(&value, bytes_.data(), n);
        bytes_ = bytes_.subspan(n);
        return value;
    }

    [[nodiscard]] std::span<const std::uint8_t> take_bytes(std::size_t count) noexcept {
        const std::size_t n = std::min(count, bytes_.size());
        const auto head = bytes_.first(n);
        bytes_ = bytes_.subspan(n);
        return head;
    }

    [[nodiscard]] std::span<const std::uint8_t> rest() noexcept { return take_bytes(bytes_.size()); }

    [[nodiscard]] constexpr bool is_empty() const noexcept { return bytes_.empty(); }
    [[nodiscard]] constexpr std::size_t remaining() const noexcept { return bytes_.size(); }

private:
    std::span<const std::uint8_t> bytes_;
};

// The allocation capability of the test context, for every arena and loader
// a harness drives.
[[nodiscard]] constexpr auto test_alloc() noexcept { return ::foundation::effects::testing::test().alloc; }

// The seed inputs of one harness.  Each harness builds them from the real
// writers, so a format change moves the seeds with it, and appends every
// minimized crash it ever found as a regression input.
using Seeds = std::vector<std::vector<std::uint8_t>>;

[[nodiscard]] inline std::vector<std::uint8_t> text_bytes(std::string_view text) {
    return std::vector<std::uint8_t>(text.begin(), text.end());
}

// Appends the object representation of a trivially copyable value, the way
// the matching reader takes it apart.
template <typename T>
    requires std::is_trivially_copyable_v<T>
inline void append_raw(std::vector<std::uint8_t>& out, const T& value) {
    const auto* first = static_cast<const std::uint8_t*>(static_cast<const void*>(&value));
    out.insert(out.end(), first, first + sizeof(T));
}

inline void append_bytes(std::vector<std::uint8_t>& out, std::span<const std::uint8_t> bytes) {
    out.insert(out.end(), bytes.begin(), bytes.end());
}

[[nodiscard]] inline std::string_view as_text(std::span<const std::uint8_t> bytes) noexcept {
    if (bytes.empty()) return {};
    return {static_cast<const char*>(static_cast<const void*>(bytes.data())), bytes.size()};
}

[[nodiscard]] inline std::span<const std::byte> as_bytes_view(std::span<const std::uint8_t> bytes) noexcept {
    return std::as_bytes(bytes);
}

// True when the value names an enumerator of its type.  An enum with a
// fixed underlying type holds every value of that type, so a byte read from
// outside can hold a value that names nothing.
template <typename E>
    requires std::is_scoped_enum_v<E>
[[nodiscard]] constexpr bool names_enumerator(E value) noexcept {
    return !::foundation::reflect::enumerator_name(value).empty();
}

// One directory per process under the system temporary directory.  A
// harness that needs files on disk writes them here and empties the
// directory at the start of each input, so a persistent-mode loop does not
// see the files of the input before.  A normal exit removes the directory.
// An abort leaves it, next to the crash that the fuzzer keeps.
class ScratchDir {
public:
    ScratchDir() : path_{std::filesystem::temp_directory_path() / ("crucible-fuzz-" + std::to_string(::getpid()))} {
        std::filesystem::create_directories(path_);
    }
    ScratchDir(const ScratchDir&) = delete("one directory has one owner");
    ScratchDir& operator=(const ScratchDir&) = delete("one directory has one owner");
    ~ScratchDir() {
        std::error_code ec;
        std::filesystem::remove_all(path_, ec);
    }
    [[nodiscard]] const std::filesystem::path& path() const noexcept { return path_; }

private:
    std::filesystem::path path_;
};

[[nodiscard]] inline const std::filesystem::path& scratch_dir() {
    static const ScratchDir dir;
    return dir.path();
}

inline void empty_scratch_dir() {
    std::error_code ec;
    for (const auto& entry : std::filesystem::directory_iterator(scratch_dir(), ec)) {
        std::filesystem::remove_all(entry.path(), ec);
    }
}

inline void write_file(const std::filesystem::path& path, std::span<const std::uint8_t> bytes) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!bytes.empty()) {
        out.write(static_cast<const char*>(static_cast<const void*>(bytes.data())),
                  static_cast<std::streamsize>(bytes.size()));
    }
}

}  // namespace crucible::fuzz::boundary
