#pragma once

// ── crucible::algebra::lattices::SeqPrefixLattice<Element> ──────────
//
// Sequence-prefix lattice — the foundation for AppendOnly<T> per
// 25_04_2026.md §2.3:
//
//     template <typename T>
//     using AppendOnly = Graded<Absolute, SeqPrefixLattice<T>, T>;
//
// References:
//   Hellerstein & Alvaro     "Keeping CALM: When Distributed
//   (CACM 2020).              Consistency Is Easy." arXiv:1901.01930
//                             (Monotonic-prefix-as-coordination-freedom.)
//   Bagwell (2001).           "Ideal Hash Trees."  (Persistent
//                             append-only sequence semantics.)
//
// ── The mathematical model ──────────────────────────────────────────
//
// The natural prefix order on sequences ⟦Element⟧* is:
//
//     u ⊑ v   iff   u is a prefix of v
//
// This is a partial order on the free monoid generated by Element:
//   - reflexive:    u ⊑ u
//   - antisymmetric: u ⊑ v ∧ v ⊑ u ⇒ u = v
//   - transitive:   u ⊑ v ∧ v ⊑ w ⇒ u ⊑ w
//
// Under prefix order:
//   - bottom = ε (empty sequence) — every sequence has ε as prefix.
//   - top    = no greatest element in the general unbounded case.
//   - meet   = longest common prefix (always exists).
//   - join   = NOT GENERAL — two sequences with no common extension
//              have no join (the prefix order is only a SEMI-lattice).
//
// ── Why the encoding uses LENGTH, not the sequence ─────────────────
//
// In AppendOnly<T>'s actual usage, all observed prefixes belong to a
// SINGLE underlying sequence — a stream that grows monotonically as
// elements are appended.  Two views of "current state" of one
// AppendOnly stream are necessarily prefixes of the same canonical
// sequence; in that universe the prefix order COLLAPSES to a TOTAL
// order on length (longer prefix ⇔ later state).  Joins always exist
// (the longer one), making the structure a true LATTICE.
//
// Encoding the grade as `length` rather than as the full sequence:
//
//   1. Constant 8 bytes per grade (a size_t) instead of O(N) bytes
//      for the actual prefix.  Critical for the AppendOnly<T> use
//      case where T is a large element type and the sequence may
//      have millions of entries.
//
//   2. Lattice operations are O(1) — `max(a.length, b.length)` —
//      versus O(min(|u|, |v|)) prefix-comparison.  Hot-path safe.
//
//   3. Composability with the rest of the algebra: length is a
//      natural number, so SeqPrefixLattice<Element> instantiates
//      to a numeric chain that the verify_bounded_lattice_axioms_at
//      rollup checks uniformly.
//
// Element appears as a TYPE-LEVEL tag — it never appears in the
// runtime grade, but it disambiguates SeqPrefixLattice<EventA> from
// SeqPrefixLattice<EventB>.  Cross-stream confusion (joining the
// length of an EventA stream with the length of an EventB stream)
// fails to compile because the lattice types are distinct.
//
// ── Why this is NOT MonotoneLattice<size_t, std::less<>> ───────────
//
// Numerically the same chain.  Semantically distinct because:
//
//   - MonotoneLattice<size_t> says "an unrelated counter".
//   - SeqPrefixLattice<Element> says "the length of a prefix of a
//     sequence of Element values".
//
// Type-level distinction matters for downstream reasoning: a Cipher
// audit can tell that AppendOnly<TraceEvent> has prefix-monotonic
// semantics (replay safety theorem applies, append-and-fork
// commutativity holds) versus a generic Monotonic<size_t> which
// could be tracking anything.  Two semantically-distinct lattices
// per the discipline of 25_04_2026.md §2.4.
//
// ── Length<Element>: strong type for the grade ─────────────────────
//
// element_type is `Length<Element>` — a struct wrapping `std::size_t`
// with phantom Element parameter.  No implicit conversion from a
// raw size_t; cross-Element comparisons fail to compile (because
// Length<EventA> and Length<EventB> are distinct types).  The
// comparison operators are spaceship-defaulted for terse leq/join/
// meet implementation.
//
//   Axiom coverage: TypeSafe — Element is a phantom type parameter;
//                   cross-Element confusion fails to compile.  The
//                   underlying length is wrapped in a struct that
//                   prevents implicit conversion from size_t.
//                   InitSafe — NSDMI ensures default construction
//                   yields length 0 (the bottom of the lattice).
//                   DetSafe — every operation is constexpr.
//   Runtime cost:   sizeof(Length<Element>) == sizeof(std::size_t)
//                   (8 bytes on 64-bit).  Empty Element doesn't
//                   matter — Length<Element> is a struct holding
//                   one size_t.  Dynamic-grade lattice; no EBO
//                   collapse on the grade.
//
// See ALGEBRA-3 (Graded.h), ALGEBRA-2 (Lattice.h);
// MIGRATE-6 (#466) for the AppendOnly<T> alias instantiation;
// the existing safety::AppendOnly for the runtime container that
// supplies the elements being prefix-counted.

#include <crucible/algebra/Graded.h>
#include <crucible/algebra/Lattice.h>

#include <algorithm>
#include <compare>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <string_view>
#include <type_traits>

namespace crucible::algebra::lattices {

// ── Length<Element>: phantom-typed prefix-length wrapper ────────────
template <typename Element>
struct Length {
    std::size_t length{0};

    // Convenience static factory — preferred over brace-init at call
    // sites for readability ("Length<Event>::at(5)" reads better than
    // "Length<Event>{5}" especially in template-heavy contexts).  No
    // contract beyond the natural-number domain of size_t; SIZE_MAX
    // is the lattice top so it's a valid input here, though most
    // callers want the named SeqPrefixLattice<Element>::top() form
    // when expressing the "no-upper-bound" case.
    [[nodiscard]] static constexpr Length at(std::size_t n) noexcept {
        return Length{n};
    }

    [[nodiscard]] friend constexpr auto operator<=>(Length, Length) noexcept = default;
    [[nodiscard]] friend constexpr bool operator==(Length, Length) noexcept = default;
};

// ── SeqPrefixLattice<Element> ───────────────────────────────────────
template <typename Element>
struct SeqPrefixLattice {
    using element_type           = Length<Element>;
    using sequence_element_type  = Element;

    [[nodiscard]] static constexpr element_type bottom() noexcept {
        return element_type{0};
    }
    [[nodiscard]] static constexpr element_type top() noexcept {
        // No mathematical top in the unbounded prefix order, but the
        // type system needs a representative ceiling for at_top
        // queries and for spec-test bounds witnesses.  SIZE_MAX is
        // the practical ceiling — any longer sequence would already
        // have overflowed the size representation.
        return element_type{std::numeric_limits<std::size_t>::max()};
    }
    [[nodiscard]] static constexpr bool leq(element_type a, element_type b) noexcept {
        return a.length <= b.length;
    }
    [[nodiscard]] static constexpr element_type join(element_type a, element_type b) noexcept {
        return element_type{std::max(a.length, b.length)};
    }
    [[nodiscard]] static constexpr element_type meet(element_type a, element_type b) noexcept {
        return element_type{std::min(a.length, b.length)};
    }

    [[nodiscard]] static consteval std::string_view name() noexcept {
        return "SeqPrefixLattice";
    }

    // ── Derived-grade opt-in (algebra/Graded.h §"derived-grade") ────
    //
    // The lattice element (a prefix length) is structurally already
    // present inside any container we wrap — `Container::size()`
    // returns it in O(1).  Storing it AGAIN as a separate Graded
    // grade field would duplicate information.
    //
    // Opting into LatticeDerivesGrade<L, T> via this static method
    // tells the Graded substrate to use its derived-grade
    // specialization: store only the value (the container), compute
    // the grade on demand from `c.size()`.  Result: AppendOnly<T,
    // std::vector> retains sizeof(std::vector<T>) — no +8 byte
    // regression, no Arena cache-line breakage.
    //
    // The Container template parameter accepts any type with a
    // `.size()` member returning size_t-convertible — std::vector,
    // std::inplace_vector, arena-backed sequences, or any custom
    // append-only Storage that AppendOnly might be specialized over.
    template <typename Container>
        requires requires (Container const& c) {
            { c.size() } -> std::convertible_to<std::size_t>;
        }
    [[nodiscard]] static constexpr element_type grade_of(Container const& c) noexcept {
        return element_type{c.size()};
    }
};

// ── Self-test ───────────────────────────────────────────────────────
namespace detail::seq_prefix_lattice_self_test {

// Two distinct Element witnesses — used to verify that
// SeqPrefixLattice<EventA> and SeqPrefixLattice<EventB> are distinct
// types and that their Length<...> grades cannot cross-compare.
struct EventA {};
struct EventB {};

using LatA = SeqPrefixLattice<EventA>;
using LatB = SeqPrefixLattice<EventB>;

// Concept conformance.
static_assert(Lattice<LatA>);
static_assert(BoundedBelowLattice<LatA>);
static_assert(BoundedAboveLattice<LatA>);
static_assert(BoundedLattice<LatA>);
static_assert(Lattice<LatB>);
static_assert(BoundedLattice<LatB>);

// Cross-Element type distinctness — load-bearing for the semantic
// guarantee that EventA streams and EventB streams cannot be
// confused at the type level.
static_assert(!std::is_same_v<LatA, LatB>);
static_assert(!std::is_same_v<LatA::element_type, LatB::element_type>);
static_assert(!std::is_convertible_v<LatA::element_type, LatB::element_type>);
static_assert(!std::is_convertible_v<LatB::element_type, LatA::element_type>);

// Length<E> is NOT empty (carries a size_t) and is exactly that size.
static_assert(!std::is_empty_v<LatA::element_type>);
static_assert(sizeof(LatA::element_type) == sizeof(std::size_t));
static_assert(alignof(LatA::element_type) == alignof(std::size_t));

// element_type defaults to Length{0} via NSDMI — the lattice's
// bottom element.  Verified against bottom() identity.
static_assert(LatA::element_type{} == LatA::bottom());
static_assert(LatA::bottom().length == 0);
static_assert(LatA::top().length    == std::numeric_limits<std::size_t>::max());

// Length comparison is by length (default spaceship).
static_assert(Length<EventA>{0}   <  Length<EventA>{1});
static_assert(Length<EventA>{100} == Length<EventA>{100});
static_assert(Length<EventA>{200} >  Length<EventA>{199});

// Convenience static factory.
static_assert(Length<EventA>::at(0)   == Length<EventA>{0});
static_assert(Length<EventA>::at(100) == Length<EventA>{100});
static_assert(Length<EventA>::at(0)   == LatA::bottom());

// ── Lattice ops at representative witnesses ─────────────────────────
constexpr Length<EventA> ε       = LatA::bottom();
constexpr Length<EventA> short_  = Length<EventA>{1};
constexpr Length<EventA> mid     = Length<EventA>{1024};
constexpr Length<EventA> longish = Length<EventA>{1'000'000};
constexpr Length<EventA> ω       = LatA::top();

static_assert(LatA::leq(ε, short_));
static_assert(LatA::leq(ε, ω));
static_assert(LatA::leq(short_, mid));
static_assert(LatA::leq(mid, longish));
static_assert(LatA::leq(longish, ω));
static_assert(LatA::leq(ε, ε));        // reflexive at bottom
static_assert(LatA::leq(ω, ω));        // reflexive at top
static_assert(!LatA::leq(short_, ε));  // 1 not ⊑ 0
static_assert(!LatA::leq(ω, longish)); // ∞ not ⊑ 1M

static_assert(LatA::join(short_, mid)  == mid);
static_assert(LatA::join(mid, short_)  == mid);
static_assert(LatA::join(ε, ω)         == ω);
static_assert(LatA::meet(short_, mid)  == short_);
static_assert(LatA::meet(ε, ω)         == ε);

// ── EXHAUSTIVE-WITHIN-WITNESS-SET axiom coverage ────────────────────
//
// 5 witnesses → 125 triples; verify_bounded_lattice_axioms_at rolls
// the 13-axiom family per triple.  Below picks representative
// triples covering the boundary, mid, and descending paths.
static_assert(verify_bounded_lattice_axioms_at<LatA>(ε,       ε,       ε));
static_assert(verify_bounded_lattice_axioms_at<LatA>(ε,       short_,  mid));
static_assert(verify_bounded_lattice_axioms_at<LatA>(short_,  mid,     longish));
static_assert(verify_bounded_lattice_axioms_at<LatA>(mid,     longish, ω));
static_assert(verify_bounded_lattice_axioms_at<LatA>(ω,       ω,       ω));
static_assert(verify_bounded_lattice_axioms_at<LatA>(longish, mid,     short_));   // descending
static_assert(verify_bounded_lattice_axioms_at<LatA>(ε,       mid,     ω));        // span
static_assert(verify_bounded_lattice_axioms_at<LatA>(ω,       ε,       longish));  // mixed

// ── Append semantics: bottom + new entries ⊑ longer ─────────────────
//
// Bumping the length corresponds to the AppendOnly pattern:
// bottom ⊑ ε+1 ⊑ ε+2 ⊑ ε+3 ... — strictly ascending.
constexpr Length<EventA> bumped_1 = LatA::join(ε, Length<EventA>{1});
constexpr Length<EventA> bumped_2 = LatA::join(bumped_1, Length<EventA>{2});
constexpr Length<EventA> bumped_3 = LatA::join(bumped_2, Length<EventA>{3});

static_assert(LatA::leq(ε, bumped_1));
static_assert(LatA::leq(bumped_1, bumped_2));
static_assert(LatA::leq(bumped_2, bumped_3));
static_assert(LatA::leq(ε, bumped_3));   // transitive append

// Diagnostic name.
static_assert(LatA::name() == "SeqPrefixLattice");
static_assert(LatB::name() == "SeqPrefixLattice");

// sequence_element_type alias correct.
static_assert(std::is_same_v<LatA::sequence_element_type, EventA>);
static_assert(std::is_same_v<LatB::sequence_element_type, EventB>);

// ── Layout — NOT zero-overhead (dynamic-grade) ──────────────────────
//
// element_type is Length<Element> = struct{size_t length{0}}; non-empty.
// Graded<Absolute, SeqPrefixLattice<Element>, T> stores both the inner
// value AND the 8-byte length grade.  CRUCIBLE_GRADED_LAYOUT_INVARIANT
// does NOT apply — dynamic grade by structural necessity.
struct OneByteValue { char c{0}; };
struct EightByteValue { unsigned long long v{0}; };

template <typename T>
using AppendOnlyGraded =
    Graded<ModalityKind::Absolute, SeqPrefixLattice<EventA>, T>;

// 1B value + 8B grade with 8B alignment → 16 bytes (1 + 7 padding + 8).
static_assert(sizeof(AppendOnlyGraded<OneByteValue>) ==
              sizeof(OneByteValue) + sizeof(LatA::element_type) + 7);

// 8B value + 8B grade with 8B alignment → 16 bytes exactly.
static_assert(sizeof(AppendOnlyGraded<EightByteValue>) ==
              sizeof(EightByteValue) + sizeof(LatA::element_type));

// ── Runtime smoke test ──────────────────────────────────────────────
//
// Per feedback_algebra_runtime_smoke_test_discipline memory: every
// algebra/lattices/ header MUST exercise lattice ops AND
// Graded<...,L,T>::weaken/compose with non-constant arguments to
// catch consteval/SFINAE traps that pure static_assert tests miss.
inline void runtime_smoke_test() {
    // Non-constant length values.
    std::size_t n_a = 5;
    std::size_t n_b = 17;
    Length<EventA> a{n_a};
    Length<EventA> b{n_b};

    // Lattice ops at runtime.
    [[maybe_unused]] bool                l = LatA::leq(a, b);
    [[maybe_unused]] LatA::element_type  j = LatA::join(a, b);
    [[maybe_unused]] LatA::element_type  m = LatA::meet(a, b);
    [[maybe_unused]] LatA::element_type  bot = LatA::bottom();
    [[maybe_unused]] LatA::element_type  top = LatA::top();

    // Graded<Absolute, SeqPrefixLattice<EventA>, T> at runtime.
    OneByteValue v{42};
    AppendOnlyGraded<OneByteValue> initial{v, LatA::bottom()};
    auto widened   = initial.weaken(a);                  // weaken to length 5
    auto widened2  = widened.weaken(b);                  // advance to length 17
    auto composed  = initial.compose(widened2);          // join with longer
    auto rv_widen  = std::move(widened2).weaken(b);      // rvalue-this weaken
    auto rv_comp   = std::move(initial).compose(composed); // rvalue-this compose

    [[maybe_unused]] auto g1 = composed.grade();
    [[maybe_unused]] auto v1 = composed.peek().c;
    [[maybe_unused]] auto v2 = std::move(rv_comp).consume().c;
    [[maybe_unused]] auto g2 = rv_widen.grade();
}

}  // namespace detail::seq_prefix_lattice_self_test

}  // namespace crucible::algebra::lattices
