// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 34 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fh3 role k1+drop@0/peer/s0:
namespace r612 {
using A = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using session_oracle_nest524 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest524>;
}  // namespace r612
// session_oracle fixy.wire case fh3 role k1+drop@0/peer/s1:
namespace r613 {
using A = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using session_oracle_nest525 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest525>;
}  // namespace r613
// session_oracle fixy.wire case fh3 role k1+drop@0/view/s0:
namespace r614 {
using A = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using session_oracle_nest526 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest526>;
}  // namespace r614
// session_oracle fixy.wire case fh3 role k1+drop@0/view/s1:
namespace r615 {
using A = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using session_oracle_nest527 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest527>;
}  // namespace r615
// session_oracle fixy.wire case fh3 role k2-add@0/peer/s0:
namespace r616 {
using session_oracle_nest528 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest528>;
using session_oracle_nest529 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest529>;
}  // namespace r616
// session_oracle fixy.wire case fh3 role k2-add@0/peer/s1:
namespace r617 {
using session_oracle_nest530 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest530>;
using session_oracle_nest531 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest531>;
}  // namespace r617
// session_oracle fixy.wire case fh3 role k2-add@0/view/s0:
namespace r618 {
using session_oracle_nest532 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest532>;
using session_oracle_nest533 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest533>;
}  // namespace r618
// session_oracle fixy.wire case fh3 role k2-add@0/view/s1:
namespace r619 {
using session_oracle_nest534 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest534>;
using session_oracle_nest535 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest535>;
}  // namespace r619
// session_oracle fixy.wire case fh3 role k5+step@0/peer/s0:
namespace r620 {
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using session_oracle_nest536 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest536>;
}  // namespace r620
// session_oracle fixy.wire case fh3 role k5+step@0/peer/s1:
namespace r621 {
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using session_oracle_nest537 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest537>;
}  // namespace r621
// session_oracle fixy.wire case fh3 role k5+step@0/view/s0:
namespace r622 {
using A = fs::Loop<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> > >;
using session_oracle_nest538 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest538>;
}  // namespace r622
// session_oracle fixy.wire case fh3 role k5+step@0/view/s1:
namespace r623 {
using A = fs::Loop<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> > >;
using session_oracle_nest539 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest539>;
}  // namespace r623
// session_oracle fixy.wire case fh3 role k6+permall/peer/s0:
namespace r624 {
using session_oracle_nest540 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using A = fs::Loop<session_oracle_nest540>;
using session_oracle_nest541 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest541>;
}  // namespace r624
// session_oracle fixy.wire case fh3 role k6+permall/peer/s1:
namespace r625 {
using session_oracle_nest542 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using A = fs::Loop<session_oracle_nest542>;
using session_oracle_nest543 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest543>;
}  // namespace r625
// session_oracle fixy.wire case fh3 role k6+permall/view/s0:
namespace r626 {
using session_oracle_nest544 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> > >;
using A = fs::Loop<session_oracle_nest544>;
using session_oracle_nest545 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest545>;
}  // namespace r626
// session_oracle fixy.wire case fh3 role k6+permall/view/s1:
namespace r627 {
using session_oracle_nest546 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> > >;
using A = fs::Loop<session_oracle_nest546>;
using session_oracle_nest547 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Loop<session_oracle_nest547>;
}  // namespace r627
// session_oracle fixy.wire case fh3 role k6-permall/peer/s0:
namespace r628 {
using session_oracle_nest548 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest548>;
using session_oracle_nest549 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using B = fs::Loop<session_oracle_nest549>;
}  // namespace r628
// session_oracle fixy.wire case fh3 role k6-permall/peer/s1:
namespace r629 {
using session_oracle_nest550 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest550>;
using session_oracle_nest551 = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >;
using B = fs::Loop<session_oracle_nest551>;
}  // namespace r629
// session_oracle fixy.wire case fh3 role k6-permall/view/s0:
namespace r630 {
using session_oracle_nest552 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest552>;
using session_oracle_nest553 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> > >;
using B = fs::Loop<session_oracle_nest553>;
}  // namespace r630
// session_oracle fixy.wire case fh3 role k6-permall/view/s1:
namespace r631 {
using session_oracle_nest554 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Continue> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<session_oracle_nest554>;
using session_oracle_nest555 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Continue> > >;
using B = fs::Loop<session_oracle_nest555>;
}  // namespace r631

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fh3 role k1+drop@0/peer/s0:", &::session_oracle::wire::run_pair<r612::A, r612::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k1+drop@0/peer/s1:", &::session_oracle::wire::run_pair<r613::A, r613::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k1+drop@0/view/s0:", &::session_oracle::wire::run_pair<r614::A, r614::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k1+drop@0/view/s1:", &::session_oracle::wire::run_pair<r615::A, r615::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k2-add@0/peer/s0:", &::session_oracle::wire::run_pair<r616::A, r616::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k2-add@0/peer/s1:", &::session_oracle::wire::run_pair<r617::A, r617::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k2-add@0/view/s0:", &::session_oracle::wire::run_pair<r618::A, r618::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k2-add@0/view/s1:", &::session_oracle::wire::run_pair<r619::A, r619::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k5+step@0/peer/s0:", &::session_oracle::wire::run_pair<r620::A, r620::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k5+step@0/peer/s1:", &::session_oracle::wire::run_pair<r621::A, r621::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k5+step@0/view/s0:", &::session_oracle::wire::run_pair<r622::A, r622::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k5+step@0/view/s1:", &::session_oracle::wire::run_pair<r623::A, r623::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6+permall/peer/s0:", &::session_oracle::wire::run_pair<r624::A, r624::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6+permall/peer/s1:", &::session_oracle::wire::run_pair<r625::A, r625::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6+permall/view/s0:", &::session_oracle::wire::run_pair<r626::A, r626::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6+permall/view/s1:", &::session_oracle::wire::run_pair<r627::A, r627::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6-permall/peer/s0:", &::session_oracle::wire::run_pair<r628::A, r628::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6-permall/peer/s1:", &::session_oracle::wire::run_pair<r629::A, r629::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6-permall/view/s0:", &::session_oracle::wire::run_pair<r630::A, r630::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh3 role k6-permall/view/s1:", &::session_oracle::wire::run_pair<r631::A, r631::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_34() { return rows; }

}  // namespace session_oracle::fixy_wire
