// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 6 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr12 role k5+step@0/peer/s0:
namespace r104 {
using session_oracle_nest100 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest100> >;
using session_oracle_nest101 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest102 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest101> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest102, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r104
// session_oracle fixy.wire case fr12 role k5+step@0/peer/s1:
namespace r105 {
using session_oracle_nest103 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest103> >;
using session_oracle_nest104 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest105 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest104> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest105, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r105
// session_oracle fixy.wire case fr12 role k5+step@0/view/s0:
namespace r106 {
using session_oracle_nest106 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > > > > >;
using A = fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest106>;
using session_oracle_nest107 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest107>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
}  // namespace r106
// session_oracle fixy.wire case fr12 role k5+step@0/view/s1:
namespace r107 {
using session_oracle_nest108 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > > > > >;
using A = fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest108>;
using session_oracle_nest109 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest109>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
}  // namespace r107
// session_oracle fixy.wire case fr12 role k6+permall/peer/s0:
namespace r108 {
using session_oracle_nest110 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using session_oracle_nest111 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, session_oracle_nest110, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, session_oracle_nest111>;
using session_oracle_nest112 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest113 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest112> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest113, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r108
// session_oracle fixy.wire case fr12 role k6+permall/peer/s1:
namespace r109 {
using session_oracle_nest114 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using session_oracle_nest115 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, session_oracle_nest114, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, session_oracle_nest115>;
using session_oracle_nest116 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest117 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest116> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest117, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r109
// session_oracle fixy.wire case fr12 role k6+permall/view/s0:
namespace r110 {
using session_oracle_nest118 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > >;
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest118> >;
using session_oracle_nest119 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest119>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
}  // namespace r110
// session_oracle fixy.wire case fr12 role k6+permall/view/s1:
namespace r111 {
using session_oracle_nest120 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > >;
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest120> >;
using session_oracle_nest121 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest121>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
}  // namespace r111
// session_oracle fixy.wire case fr12 role k6-permall/peer/s0:
namespace r112 {
using session_oracle_nest122 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest123 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest122> >;
using A = fs::Select<session_oracle_nest123, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using session_oracle_nest124 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using session_oracle_nest125 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<session_oracle_nest124, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, session_oracle_nest125>;
}  // namespace r112
// session_oracle fixy.wire case fr12 role k6-permall/peer/s1:
namespace r113 {
using session_oracle_nest126 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using session_oracle_nest127 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, session_oracle_nest126> >;
using A = fs::Select<session_oracle_nest127, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using session_oracle_nest128 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using session_oracle_nest129 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Select<session_oracle_nest128, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, session_oracle_nest129>;
}  // namespace r113
// session_oracle fixy.wire case fr12 role k6-permall/view/s0:
namespace r114 {
using session_oracle_nest130 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > > > > >;
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest130>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
using session_oracle_nest131 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest131> >;
}  // namespace r114
// session_oracle fixy.wire case fr12 role k6-permall/view/s1:
namespace r115 {
using session_oracle_nest132 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Nat, fs::Continue> > > > > >;
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest132>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
using session_oracle_nest133 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Nat, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, session_oracle_nest133> >;
}  // namespace r115

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr12 role k5+step@0/peer/s0:", &::session_oracle::wire::run_pair<r104::A, r104::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k5+step@0/peer/s1:", &::session_oracle::wire::run_pair<r105::A, r105::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr12 role k5+step@0/view/s0:", &::session_oracle::wire::run_pair<r106::A, r106::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k5+step@0/view/s1:", &::session_oracle::wire::run_pair<r107::A, r107::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6+permall/peer/s0:", &::session_oracle::wire::run_pair<r108::A, r108::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6+permall/peer/s1:", &::session_oracle::wire::run_pair<r109::A, r109::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6+permall/view/s0:", &::session_oracle::wire::run_pair<r110::A, r110::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6+permall/view/s1:", &::session_oracle::wire::run_pair<r111::A, r111::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6-permall/peer/s0:", &::session_oracle::wire::run_pair<r112::A, r112::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6-permall/peer/s1:", &::session_oracle::wire::run_pair<r113::A, r113::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6-permall/view/s0:", &::session_oracle::wire::run_pair<r114::A, r114::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr12 role k6-permall/view/s1:", &::session_oracle::wire::run_pair<r115::A, r115::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_6() { return rows; }

}  // namespace session_oracle::fixy_wire
