// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 32 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fa38 role k1-drop@0/peer/s0:
namespace r572 {
using session_oracle_nest484 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest484> >;
using session_oracle_nest485 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest485> >;
}  // namespace r572
// session_oracle fixy.wire case fa38 role k1-drop@0/peer/s1:
namespace r573 {
using session_oracle_nest486 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest486> >;
using session_oracle_nest487 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest487> >;
}  // namespace r573
// session_oracle fixy.wire case fa38 role k1-drop@0/view/s0:
namespace r574 {
using session_oracle_nest488 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest488> >;
using session_oracle_nest489 = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, session_oracle_nest489> >;
}  // namespace r574
// session_oracle fixy.wire case fa38 role k1-drop@0/view/s1:
namespace r575 {
using session_oracle_nest490 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest490> >;
using session_oracle_nest491 = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, session_oracle_nest491> >;
}  // namespace r575
// session_oracle fixy.wire case fa38 role k2+add@0/peer/s0:
namespace r576 {
using session_oracle_nest492 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest492> >;
using session_oracle_nest493 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest493> >;
}  // namespace r576
// session_oracle fixy.wire case fa38 role k2+add@0/peer/s1:
namespace r577 {
using session_oracle_nest494 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest494> >;
using session_oracle_nest495 = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest495> >;
}  // namespace r577
// session_oracle fixy.wire case fa38 role k2+add@0/view/s0:
namespace r578 {
using session_oracle_nest496 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest496> >;
using session_oracle_nest497 = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, session_oracle_nest497> >;
}  // namespace r578
// session_oracle fixy.wire case fa38 role k2+add@0/view/s1:
namespace r579 {
using session_oracle_nest498 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest498> >;
using session_oracle_nest499 = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, session_oracle_nest499> >;
}  // namespace r579
// session_oracle fixy.wire case fa38 role k5-step@0/peer/s0:
namespace r580 {
using session_oracle_nest500 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest500> >;
using session_oracle_nest501 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest501>;
}  // namespace r580
// session_oracle fixy.wire case fa38 role k5-step@0/peer/s1:
namespace r581 {
using session_oracle_nest502 = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest502> >;
using session_oracle_nest503 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest503>;
}  // namespace r581
// session_oracle fixy.wire case fa38 role k5-step@0/view/s0:
namespace r582 {
using session_oracle_nest504 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest504> >;
using session_oracle_nest505 = fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, session_oracle_nest505>;
}  // namespace r582
// session_oracle fixy.wire case fa38 role k5-step@0/view/s1:
namespace r583 {
using session_oracle_nest506 = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, session_oracle_nest506> >;
using session_oracle_nest507 = fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Recv<session_oracle::Bool, session_oracle_nest507>;
}  // namespace r583
// session_oracle fixy.wire case fh2 role k0+perm@0/peer/s0:
namespace r584 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r584
// session_oracle fixy.wire case fh2 role k0+perm@0/peer/s1:
namespace r585 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r585
// session_oracle fixy.wire case fh2 role k0+perm@0/view/s0:
namespace r586 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r586
// session_oracle fixy.wire case fh2 role k0+perm@0/view/s1:
namespace r587 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r587
// session_oracle fixy.wire case fh2 role k0-perm@0/peer/s0:
namespace r588 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r588
// session_oracle fixy.wire case fh2 role k0-perm@0/peer/s1:
namespace r589 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r589
// session_oracle fixy.wire case fh2 role k0-perm@0/view/s0:
namespace r590 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r590
// session_oracle fixy.wire case fh2 role k0-perm@0/view/s1:
namespace r591 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r591

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fa38 role k1-drop@0/peer/s0:", &::session_oracle::wire::run_pair<r572::A, r572::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k1-drop@0/peer/s1:", &::session_oracle::wire::run_pair<r573::A, r573::B, 1>, "ok"},
    {"session_oracle fixy.wire case fa38 role k1-drop@0/view/s0:", &::session_oracle::wire::run_pair<r574::A, r574::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k1-drop@0/view/s1:", &::session_oracle::wire::run_pair<r575::A, r575::B, 1>, "ok"},
    {"session_oracle fixy.wire case fa38 role k2+add@0/peer/s0:", &::session_oracle::wire::run_pair<r576::A, r576::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k2+add@0/peer/s1:", &::session_oracle::wire::run_pair<r577::A, r577::B, 1>, "ok"},
    {"session_oracle fixy.wire case fa38 role k2+add@0/view/s0:", &::session_oracle::wire::run_pair<r578::A, r578::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k2+add@0/view/s1:", &::session_oracle::wire::run_pair<r579::A, r579::B, 1>, "ok"},
    {"session_oracle fixy.wire case fa38 role k5-step@0/peer/s0:", &::session_oracle::wire::run_pair<r580::A, r580::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k5-step@0/peer/s1:", &::session_oracle::wire::run_pair<r581::A, r581::B, 1>, "ok"},
    {"session_oracle fixy.wire case fa38 role k5-step@0/view/s0:", &::session_oracle::wire::run_pair<r582::A, r582::B, 0>, "ok"},
    {"session_oracle fixy.wire case fa38 role k5-step@0/view/s1:", &::session_oracle::wire::run_pair<r583::A, r583::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r584::A, r584::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r585::A, r585::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r586::A, r586::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r587::A, r587::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r588::A, r588::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r589::A, r589::B, 1>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r590::A, r590::B, 0>, "ok"},
    {"session_oracle fixy.wire case fh2 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r591::A, r591::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_32() { return rows; }

}  // namespace session_oracle::fixy_wire
