// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 3 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr4 role k6+permall/peer/s0:
namespace r60 {
using session_oracle_nest36 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest36> >;
using session_oracle_nest37 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest37> >;
}  // namespace r60
// session_oracle fixy.wire case fr4 role k6+permall/peer/s1:
namespace r61 {
using session_oracle_nest38 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest38> >;
using session_oracle_nest39 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest39> >;
}  // namespace r61
// session_oracle fixy.wire case fr4 role k6+permall/view/s0:
namespace r62 {
using session_oracle_nest40 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
using A = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, session_oracle_nest40> >;
using session_oracle_nest41 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > > >;
using B = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, session_oracle_nest41> >;
}  // namespace r62
// session_oracle fixy.wire case fr4 role k6+permall/view/s1:
namespace r63 {
using session_oracle_nest42 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
using A = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, session_oracle_nest42> >;
using session_oracle_nest43 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > > >;
using B = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, session_oracle_nest43> >;
}  // namespace r63
// session_oracle fixy.wire case fr4 role k6-permall/peer/s0:
namespace r64 {
using session_oracle_nest44 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest44> >;
using session_oracle_nest45 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest45> >;
}  // namespace r64
// session_oracle fixy.wire case fr4 role k6-permall/peer/s1:
namespace r65 {
using session_oracle_nest46 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest46> >;
using session_oracle_nest47 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest47> >;
}  // namespace r65
// session_oracle fixy.wire case fr4 role k6-permall/view/s0:
namespace r66 {
using session_oracle_nest48 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > > >;
using A = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, session_oracle_nest48> >;
using session_oracle_nest49 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
using B = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, session_oracle_nest49> >;
}  // namespace r66
// session_oracle fixy.wire case fr4 role k6-permall/view/s1:
namespace r67 {
using session_oracle_nest50 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > > >;
using A = fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, session_oracle_nest50> >;
using session_oracle_nest51 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
using B = fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, session_oracle_nest51> >;
}  // namespace r67
// session_oracle fixy.wire case fr10 role k0+perm@0/peer/s0:
namespace r68 {
using A = fs::Loop<fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r68
// session_oracle fixy.wire case fr10 role k0+perm@0/peer/s1:
namespace r69 {
using A = fs::Loop<fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r69
// session_oracle fixy.wire case fr10 role k0+perm@0/view/s0:
namespace r70 {
using A = fs::Loop<fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r70
// session_oracle fixy.wire case fr10 role k0+perm@0/view/s1:
namespace r71 {
using A = fs::Loop<fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r71
// session_oracle fixy.wire case fr10 role k0-perm@0/peer/s0:
namespace r72 {
using A = fs::Loop<fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r72
// session_oracle fixy.wire case fr10 role k0-perm@0/peer/s1:
namespace r73 {
using A = fs::Loop<fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r73
// session_oracle fixy.wire case fr10 role k0-perm@0/view/s0:
namespace r74 {
using A = fs::Loop<fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r74
// session_oracle fixy.wire case fr10 role k0-perm@0/view/s1:
namespace r75 {
using A = fs::Loop<fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue> > >;
using B = fs::Loop<fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue> > >;
}  // namespace r75

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr4 role k6+permall/peer/s0:", &::session_oracle::wire::run_pair<r60::A, r60::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6+permall/peer/s1:", &::session_oracle::wire::run_pair<r61::A, r61::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6+permall/view/s0:", &::session_oracle::wire::run_pair<r62::A, r62::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6+permall/view/s1:", &::session_oracle::wire::run_pair<r63::A, r63::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6-permall/peer/s0:", &::session_oracle::wire::run_pair<r64::A, r64::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6-permall/peer/s1:", &::session_oracle::wire::run_pair<r65::A, r65::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6-permall/view/s0:", &::session_oracle::wire::run_pair<r66::A, r66::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr4 role k6-permall/view/s1:", &::session_oracle::wire::run_pair<r67::A, r67::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r68::A, r68::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r69::A, r69::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r70::A, r70::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r71::A, r71::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r72::A, r72::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r73::A, r73::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r74::A, r74::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr10 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r75::A, r75::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_3() { return rows; }

}  // namespace session_oracle::fixy_wire
