// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 17 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr37 role k2-add@0/peer/s0:
namespace r304 {
using session_oracle_nest274 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest275 = fs::Select<session_oracle_nest274, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest275>;
using session_oracle_nest276 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest277 = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest276, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest277>;
}  // namespace r304
// session_oracle fixy.wire case fr37 role k2-add@0/peer/s1:
namespace r305 {
using session_oracle_nest278 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest279 = fs::Select<session_oracle_nest278, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest279>;
using session_oracle_nest280 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest281 = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest280, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest281>;
}  // namespace r305
// session_oracle fixy.wire case fr37 role k2-add@0/view/s0:
namespace r306 {
using session_oracle_nest282 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Nat, fs::End> > > > >;
using A = fs::Recv<session_oracle::Nat, session_oracle_nest282>;
using session_oracle_nest283 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Send<session_oracle::Nat, session_oracle_nest283>;
}  // namespace r306
// session_oracle fixy.wire case fr37 role k2-add@0/view/s1:
namespace r307 {
using session_oracle_nest284 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Nat, fs::End> > > > >;
using A = fs::Recv<session_oracle::Nat, session_oracle_nest284>;
using session_oracle_nest285 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::End> > > >, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> >;
using B = fs::Send<session_oracle::Nat, session_oracle_nest285>;
}  // namespace r307
// session_oracle fixy.wire case fr37 role k5+step@0/peer/s0:
namespace r308 {
using session_oracle_nest286 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest286>;
using session_oracle_nest287 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest288 = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest287, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest288>;
}  // namespace r308
// session_oracle fixy.wire case fr37 role k5+step@0/peer/s1:
namespace r309 {
using session_oracle_nest289 = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, session_oracle_nest289>;
using session_oracle_nest290 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > > >;
using session_oracle_nest291 = fs::Offer<fs::Sender<session_oracle::R0>, session_oracle_nest290, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, session_oracle_nest291>;
}  // namespace r309
// session_oracle fixy.wire case fr37 role k5+step@0/view/s0:
namespace r310 {
using A = fs::Recv<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > > > >;
using session_oracle_nest292 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::End> > > > >;
using B = fs::Send<session_oracle::Nat, session_oracle_nest292>;
}  // namespace r310
// session_oracle fixy.wire case fr37 role k5+step@0/view/s1:
namespace r311 {
using A = fs::Recv<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > > > > >;
using session_oracle_nest293 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::Recv<session_oracle::Nat, fs::End> > > > >;
using B = fs::Send<session_oracle::Nat, session_oracle_nest293>;
}  // namespace r311
// session_oracle fixy.wire case fr39 role k0+perm@0/peer/s0:
namespace r312 {
using session_oracle_nest294 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest294> >;
using session_oracle_nest295 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest295> >;
}  // namespace r312
// session_oracle fixy.wire case fr39 role k0+perm@0/peer/s1:
namespace r313 {
using session_oracle_nest296 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest296> >;
using session_oracle_nest297 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest297> >;
}  // namespace r313
// session_oracle fixy.wire case fr39 role k0+perm@0/view/s0:
namespace r314 {
using session_oracle_nest298 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest298> >;
using session_oracle_nest299 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest299> >;
}  // namespace r314
// session_oracle fixy.wire case fr39 role k0+perm@0/view/s1:
namespace r315 {
using session_oracle_nest300 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest300> >;
using session_oracle_nest301 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest301> >;
}  // namespace r315

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr37 role k2-add@0/peer/s0:", &::session_oracle::wire::run_pair<r304::A, r304::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr37 role k2-add@0/peer/s1:", &::session_oracle::wire::run_pair<r305::A, r305::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr37 role k2-add@0/view/s0:", &::session_oracle::wire::run_pair<r306::A, r306::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr37 role k2-add@0/view/s1:", &::session_oracle::wire::run_pair<r307::A, r307::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr37 role k5+step@0/peer/s0:", &::session_oracle::wire::run_pair<r308::A, r308::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr37 role k5+step@0/peer/s1:", &::session_oracle::wire::run_pair<r309::A, r309::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr37 role k5+step@0/view/s0:", &::session_oracle::wire::run_pair<r310::A, r310::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr37 role k5+step@0/view/s1:", &::session_oracle::wire::run_pair<r311::A, r311::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r312::A, r312::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r313::A, r313::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r314::A, r314::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r315::A, r315::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_17() { return rows; }

}  // namespace session_oracle::fixy_wire
