// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 7 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr14 role k0+perm@0/peer/s0:
namespace r116 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r116
// session_oracle fixy.wire case fr14 role k0+perm@0/peer/s1:
namespace r117 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r117
// session_oracle fixy.wire case fr14 role k0+perm@0/view/s0:
namespace r118 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r118
// session_oracle fixy.wire case fr14 role k0+perm@0/view/s1:
namespace r119 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r119
// session_oracle fixy.wire case fr14 role k0-perm@0/peer/s0:
namespace r120 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r120
// session_oracle fixy.wire case fr14 role k0-perm@0/peer/s1:
namespace r121 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r121
// session_oracle fixy.wire case fr14 role k0-perm@0/view/s0:
namespace r122 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r122
// session_oracle fixy.wire case fr14 role k0-perm@0/view/s1:
namespace r123 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r123
// session_oracle fixy.wire case fr14 role k1-drop@0/peer/s0:
namespace r124 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r124
// session_oracle fixy.wire case fr14 role k1-drop@0/peer/s1:
namespace r125 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r125
// session_oracle fixy.wire case fr14 role k1-drop@0/view/s0:
namespace r126 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r126
// session_oracle fixy.wire case fr14 role k1-drop@0/view/s1:
namespace r127 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> >;
}  // namespace r127
// session_oracle fixy.wire case fr14 role k2+add@0/peer/s0:
namespace r128 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r128
// session_oracle fixy.wire case fr14 role k2+add@0/peer/s1:
namespace r129 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
}  // namespace r129
// session_oracle fixy.wire case fr14 role k2+add@0/view/s0:
namespace r130 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r130
// session_oracle fixy.wire case fr14 role k2+add@0/view/s1:
namespace r131 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
}  // namespace r131
// session_oracle fixy.wire case fr14 role k5-step@0/peer/s0:
namespace r132 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>;
}  // namespace r132
// session_oracle fixy.wire case fr14 role k5-step@0/peer/s1:
namespace r133 {
using A = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>;
}  // namespace r133
// session_oracle fixy.wire case fr14 role k5-step@0/view/s0:
namespace r134 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>;
}  // namespace r134
// session_oracle fixy.wire case fr14 role k5-step@0/view/s1:
namespace r135 {
using A = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > >;
using B = fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>;
}  // namespace r135
// session_oracle fixy.wire case fr18 role k0+perm@0/peer/s0:
namespace r136 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r136
// session_oracle fixy.wire case fr18 role k0+perm@0/peer/s1:
namespace r137 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r137
// session_oracle fixy.wire case fr18 role k0+perm@0/view/s0:
namespace r138 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r138
// session_oracle fixy.wire case fr18 role k0+perm@0/view/s1:
namespace r139 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
}  // namespace r139
// session_oracle fixy.wire case fr18 role k0-perm@0/peer/s0:
namespace r140 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r140
// session_oracle fixy.wire case fr18 role k0-perm@0/peer/s1:
namespace r141 {
using A = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > >;
}  // namespace r141
// session_oracle fixy.wire case fr18 role k0-perm@0/view/s0:
namespace r142 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
}  // namespace r142
// session_oracle fixy.wire case fr18 role k0-perm@0/view/s1:
namespace r143 {
using A = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using B = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > >;
}  // namespace r143

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr14 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r116::A, r116::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r117::A, r117::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r118::A, r118::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r119::A, r119::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r120::A, r120::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r121::A, r121::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r122::A, r122::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r123::A, r123::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k1-drop@0/peer/s0:", &::session_oracle::wire::run_pair<r124::A, r124::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k1-drop@0/peer/s1:", &::session_oracle::wire::run_pair<r125::A, r125::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k1-drop@0/view/s0:", &::session_oracle::wire::run_pair<r126::A, r126::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k1-drop@0/view/s1:", &::session_oracle::wire::run_pair<r127::A, r127::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k2+add@0/peer/s0:", &::session_oracle::wire::run_pair<r128::A, r128::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k2+add@0/peer/s1:", &::session_oracle::wire::run_pair<r129::A, r129::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k2+add@0/view/s0:", &::session_oracle::wire::run_pair<r130::A, r130::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k2+add@0/view/s1:", &::session_oracle::wire::run_pair<r131::A, r131::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k5-step@0/peer/s0:", &::session_oracle::wire::run_pair<r132::A, r132::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k5-step@0/peer/s1:", &::session_oracle::wire::run_pair<r133::A, r133::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr14 role k5-step@0/view/s0:", &::session_oracle::wire::run_pair<r134::A, r134::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr14 role k5-step@0/view/s1:", &::session_oracle::wire::run_pair<r135::A, r135::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r136::A, r136::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r137::A, r137::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r138::A, r138::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r139::A, r139::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r140::A, r140::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r141::A, r141::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r142::A, r142::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr18 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r143::A, r143::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_7() { return rows; }

}  // namespace session_oracle::fixy_wire
