// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 25 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr45 role k2-add@0/peer/s0:
namespace r440 {
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> > >;
}  // namespace r440
// session_oracle fixy.wire case fr45 role k2-add@0/peer/s1:
namespace r441 {
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<10>, session_oracle::Unit>, fs::End> > >;
}  // namespace r441
// session_oracle fixy.wire case fr45 role k2-add@0/view/s0:
namespace r442 {
using A = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Bool, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >;
using B = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Bool, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> > >;
}  // namespace r442
// session_oracle fixy.wire case fr45 role k2-add@0/view/s1:
namespace r443 {
using A = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Recv<session_oracle::Bool, fs::Continue> > >, fs::Send<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::End> > > >;
using B = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Bool, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<10>, session_oracle::Unit>, fs::End> > >;
}  // namespace r443
// session_oracle fixy.wire case fr45 role k5+step@0/peer/s0:
namespace r444 {
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
}  // namespace r444
// session_oracle fixy.wire case fr45 role k5+step@0/peer/s1:
namespace r445 {
using A = fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > >;
using B = fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R0>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Continue> > >, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Label<7>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::End> > > >;
}  // namespace r445
// session_oracle fixy.wire case fr45 role k5+step@0/view/s0:
namespace r446 {
using A = fs::Recv<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
using B = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Bool, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >;
}  // namespace r446
// session_oracle fixy.wire case fr45 role k5+step@0/view/s1:
namespace r447 {
using A = fs::Recv<session_oracle::Nat, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > >;
using B = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Loop<fs::Send<session_oracle::Bool, fs::Continue> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::End> > > >;
}  // namespace r447
// session_oracle fixy.wire case fr46 role k0+perm@0/peer/s0:
namespace r448 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
}  // namespace r448
// session_oracle fixy.wire case fr46 role k0+perm@0/peer/s1:
namespace r449 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
}  // namespace r449
// session_oracle fixy.wire case fr46 role k0+perm@0/view/s0:
namespace r450 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > >;
}  // namespace r450
// session_oracle fixy.wire case fr46 role k0+perm@0/view/s1:
namespace r451 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > >;
}  // namespace r451
// session_oracle fixy.wire case fr46 role k0-perm@0/peer/s0:
namespace r452 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r452
// session_oracle fixy.wire case fr46 role k0-perm@0/peer/s1:
namespace r453 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r453
// session_oracle fixy.wire case fr46 role k0-perm@0/view/s0:
namespace r454 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r454
// session_oracle fixy.wire case fr46 role k0-perm@0/view/s1:
namespace r455 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r455
// session_oracle fixy.wire case fr46 role k1-drop@0/peer/s0:
namespace r456 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r456
// session_oracle fixy.wire case fr46 role k1-drop@0/peer/s1:
namespace r457 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r457
// session_oracle fixy.wire case fr46 role k1-drop@0/view/s0:
namespace r458 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r458
// session_oracle fixy.wire case fr46 role k1-drop@0/view/s1:
namespace r459 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> > > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End> > >;
}  // namespace r459
// session_oracle fixy.wire case fr46 role k2+add@0/peer/s0:
namespace r460 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
}  // namespace r460
// session_oracle fixy.wire case fr46 role k2+add@0/peer/s1:
namespace r461 {
using A = fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::End> >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::End> > > >;
}  // namespace r461
// session_oracle fixy.wire case fr46 role k2+add@0/view/s0:
namespace r462 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > >;
}  // namespace r462
// session_oracle fixy.wire case fr46 role k2+add@0/view/s1:
namespace r463 {
using A = fs::Send<session_oracle::Nat, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Send<session_oracle::Nat, fs::End> >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> > >;
using B = fs::Recv<session_oracle::Nat, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::End>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Recv<session_oracle::Nat, fs::End> > > >;
}  // namespace r463

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr45 role k2-add@0/peer/s0:", &::session_oracle::wire::run_pair<r440::A, r440::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr45 role k2-add@0/peer/s1:", &::session_oracle::wire::run_pair<r441::A, r441::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr45 role k2-add@0/view/s0:", &::session_oracle::wire::run_pair<r442::A, r442::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr45 role k2-add@0/view/s1:", &::session_oracle::wire::run_pair<r443::A, r443::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr45 role k5+step@0/peer/s0:", &::session_oracle::wire::run_pair<r444::A, r444::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr45 role k5+step@0/peer/s1:", &::session_oracle::wire::run_pair<r445::A, r445::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr45 role k5+step@0/view/s0:", &::session_oracle::wire::run_pair<r446::A, r446::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr45 role k5+step@0/view/s1:", &::session_oracle::wire::run_pair<r447::A, r447::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0+perm@0/peer/s0:", &::session_oracle::wire::run_pair<r448::A, r448::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0+perm@0/peer/s1:", &::session_oracle::wire::run_pair<r449::A, r449::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0+perm@0/view/s0:", &::session_oracle::wire::run_pair<r450::A, r450::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0+perm@0/view/s1:", &::session_oracle::wire::run_pair<r451::A, r451::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r452::A, r452::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r453::A, r453::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r454::A, r454::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r455::A, r455::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k1-drop@0/peer/s0:", &::session_oracle::wire::run_pair<r456::A, r456::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k1-drop@0/peer/s1:", &::session_oracle::wire::run_pair<r457::A, r457::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k1-drop@0/view/s0:", &::session_oracle::wire::run_pair<r458::A, r458::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k1-drop@0/view/s1:", &::session_oracle::wire::run_pair<r459::A, r459::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k2+add@0/peer/s0:", &::session_oracle::wire::run_pair<r460::A, r460::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k2+add@0/peer/s1:", &::session_oracle::wire::run_pair<r461::A, r461::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr46 role k2+add@0/view/s0:", &::session_oracle::wire::run_pair<r462::A, r462::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr46 role k2+add@0/view/s1:", &::session_oracle::wire::run_pair<r463::A, r463::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_25() { return rows; }

}  // namespace session_oracle::fixy_wire
