// Generated by utils/tools/session_oracle from test/session_oracle/golden.csv.
// Do not edit.  Regenerate with utils/scripts/session-oracle.sh --regenerate, or
// re-emit after a note change with utils/scripts/session-oracle.sh --emit.
// clang-format off: the emitter owns this layout, and session_oracle_check compares it byte for byte.
// Shard 18 of the 37 shards of test_session_oracle_fixy_wire.
//
// End-to-end runs of keyed pairs over the session handle: the handle of T
// against the handle of the dual of U, over one queue of words, for pairs
// whose synchronous run is safe.  Each row pins the outcome of one run.

#include "wire_driver.h"

#include <fixy/session/Projection.h>

#include <span>

namespace session_oracle {
struct Nat {};
struct Bool {};
struct Unit {};
struct Val {};
struct R0 {};
struct R1 {};
struct R2 {};
struct R3 {};
template <unsigned I>
struct Label {};
}  // namespace session_oracle

namespace fs = ::fixy::session;

namespace session_oracle::fixy_wire {

// session_oracle fixy.wire case fr39 role k0-perm@0/peer/s0:
namespace r316 {
using session_oracle_nest302 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest302> >;
using session_oracle_nest303 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest303> >;
}  // namespace r316
// session_oracle fixy.wire case fr39 role k0-perm@0/peer/s1:
namespace r317 {
using session_oracle_nest304 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest304> >;
using session_oracle_nest305 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest305> >;
}  // namespace r317
// session_oracle fixy.wire case fr39 role k0-perm@0/view/s0:
namespace r318 {
using session_oracle_nest306 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest306> >;
using session_oracle_nest307 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest307> >;
}  // namespace r318
// session_oracle fixy.wire case fr39 role k0-perm@0/view/s1:
namespace r319 {
using session_oracle_nest308 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest308> >;
using session_oracle_nest309 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest309> >;
}  // namespace r319
// session_oracle fixy.wire case fr39 role k1-drop@0/peer/s0:
namespace r320 {
using session_oracle_nest310 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest310> >;
using session_oracle_nest311 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest311> >;
}  // namespace r320
// session_oracle fixy.wire case fr39 role k1-drop@0/peer/s1:
namespace r321 {
using session_oracle_nest312 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest312> >;
using session_oracle_nest313 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest313> >;
}  // namespace r321
// session_oracle fixy.wire case fr39 role k1-drop@0/view/s0:
namespace r322 {
using session_oracle_nest314 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest314> >;
using session_oracle_nest315 = fs::Recv<session_oracle::Bool, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Loop<session_oracle_nest315>;
}  // namespace r322
// session_oracle fixy.wire case fr39 role k1-drop@0/view/s1:
namespace r323 {
using session_oracle_nest316 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest316> >;
using session_oracle_nest317 = fs::Recv<session_oracle::Bool, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
using B = fs::Loop<session_oracle_nest317>;
}  // namespace r323
// session_oracle fixy.wire case fr39 role k2+add@0/peer/s0:
namespace r324 {
using session_oracle_nest318 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest318> >;
using session_oracle_nest319 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest319> >;
}  // namespace r324
// session_oracle fixy.wire case fr39 role k2+add@0/peer/s1:
namespace r325 {
using session_oracle_nest320 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest320> >;
using session_oracle_nest321 = fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, session_oracle_nest321> >;
}  // namespace r325
// session_oracle fixy.wire case fr39 role k2+add@0/view/s0:
namespace r326 {
using session_oracle_nest322 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest322> >;
using session_oracle_nest323 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest323> >;
}  // namespace r326
// session_oracle fixy.wire case fr39 role k2+add@0/view/s1:
namespace r327 {
using session_oracle_nest324 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > >, fs::Recv<fs::Labelled<session_oracle::Label<7>, session_oracle::Unit>, fs::End> >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest324> >;
using session_oracle_nest325 = fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > >, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Select<fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Send<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, session_oracle_nest325> >;
}  // namespace r327
// session_oracle fixy.wire case fr39 role k5-step@0/peer/s0:
namespace r328 {
using session_oracle_nest326 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest326> >;
using session_oracle_nest327 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<session_oracle_nest327>;
}  // namespace r328
// session_oracle fixy.wire case fr39 role k5-step@0/peer/s1:
namespace r329 {
using session_oracle_nest328 = fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > >, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Sender<session_oracle::R1>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::PeerMsg<session_oracle::R1, session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<fs::PeerMsg<session_oracle::R1, session_oracle::Val, session_oracle::Bool>, session_oracle_nest328> >;
using session_oracle_nest329 = fs::Recv<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Label<1>, session_oracle::Unit>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Bool>, fs::Send<fs::PeerMsg<session_oracle::R0, session_oracle::Val, session_oracle::Nat>, fs::Continue> > > > >;
using B = fs::Loop<session_oracle_nest329>;
}  // namespace r329
// session_oracle fixy.wire case fr39 role k5-step@0/view/s0:
namespace r330 {
using session_oracle_nest330 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest330> >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
}  // namespace r330
// session_oracle fixy.wire case fr39 role k5-step@0/view/s1:
namespace r331 {
using session_oracle_nest331 = fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Bool, fs::Recv<session_oracle::Nat, fs::Continue> > > >, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::Offer<fs::Recv<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Continue>, fs::Recv<fs::Labelled<session_oracle::Label<4>, session_oracle::Unit>, fs::End> > > >;
using A = fs::Loop<fs::Send<session_oracle::Bool, session_oracle_nest331> >;
using B = fs::Loop<fs::Recv<session_oracle::Bool, fs::Send<fs::Labelled<session_oracle::Label<1>, session_oracle::Unit>, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Bool, fs::Send<session_oracle::Nat, fs::Continue> > > > > >;
}  // namespace r331

namespace {

constexpr ::session_oracle::wire::Row rows[] = {
    {"session_oracle fixy.wire case fr39 role k0-perm@0/peer/s0:", &::session_oracle::wire::run_pair<r316::A, r316::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0-perm@0/peer/s1:", &::session_oracle::wire::run_pair<r317::A, r317::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0-perm@0/view/s0:", &::session_oracle::wire::run_pair<r318::A, r318::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k0-perm@0/view/s1:", &::session_oracle::wire::run_pair<r319::A, r319::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k1-drop@0/peer/s0:", &::session_oracle::wire::run_pair<r320::A, r320::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k1-drop@0/peer/s1:", &::session_oracle::wire::run_pair<r321::A, r321::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k1-drop@0/view/s0:", &::session_oracle::wire::run_pair<r322::A, r322::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k1-drop@0/view/s1:", &::session_oracle::wire::run_pair<r323::A, r323::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k2+add@0/peer/s0:", &::session_oracle::wire::run_pair<r324::A, r324::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k2+add@0/peer/s1:", &::session_oracle::wire::run_pair<r325::A, r325::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k2+add@0/view/s0:", &::session_oracle::wire::run_pair<r326::A, r326::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k2+add@0/view/s1:", &::session_oracle::wire::run_pair<r327::A, r327::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k5-step@0/peer/s0:", &::session_oracle::wire::run_pair<r328::A, r328::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k5-step@0/peer/s1:", &::session_oracle::wire::run_pair<r329::A, r329::B, 1>, "ok"},
    {"session_oracle fixy.wire case fr39 role k5-step@0/view/s0:", &::session_oracle::wire::run_pair<r330::A, r330::B, 0>, "ok"},
    {"session_oracle fixy.wire case fr39 role k5-step@0/view/s1:", &::session_oracle::wire::run_pair<r331::A, r331::B, 1>, "ok"},
};

}  // namespace

// The rows of each shard of this test.
std::span<const ::session_oracle::wire::Row> shard_rows_0();
std::span<const ::session_oracle::wire::Row> shard_rows_1();
std::span<const ::session_oracle::wire::Row> shard_rows_2();
std::span<const ::session_oracle::wire::Row> shard_rows_3();
std::span<const ::session_oracle::wire::Row> shard_rows_4();
std::span<const ::session_oracle::wire::Row> shard_rows_5();
std::span<const ::session_oracle::wire::Row> shard_rows_6();
std::span<const ::session_oracle::wire::Row> shard_rows_7();
std::span<const ::session_oracle::wire::Row> shard_rows_8();
std::span<const ::session_oracle::wire::Row> shard_rows_9();
std::span<const ::session_oracle::wire::Row> shard_rows_10();
std::span<const ::session_oracle::wire::Row> shard_rows_11();
std::span<const ::session_oracle::wire::Row> shard_rows_12();
std::span<const ::session_oracle::wire::Row> shard_rows_13();
std::span<const ::session_oracle::wire::Row> shard_rows_14();
std::span<const ::session_oracle::wire::Row> shard_rows_15();
std::span<const ::session_oracle::wire::Row> shard_rows_16();
std::span<const ::session_oracle::wire::Row> shard_rows_17();
std::span<const ::session_oracle::wire::Row> shard_rows_18();
std::span<const ::session_oracle::wire::Row> shard_rows_19();
std::span<const ::session_oracle::wire::Row> shard_rows_20();
std::span<const ::session_oracle::wire::Row> shard_rows_21();
std::span<const ::session_oracle::wire::Row> shard_rows_22();
std::span<const ::session_oracle::wire::Row> shard_rows_23();
std::span<const ::session_oracle::wire::Row> shard_rows_24();
std::span<const ::session_oracle::wire::Row> shard_rows_25();
std::span<const ::session_oracle::wire::Row> shard_rows_26();
std::span<const ::session_oracle::wire::Row> shard_rows_27();
std::span<const ::session_oracle::wire::Row> shard_rows_28();
std::span<const ::session_oracle::wire::Row> shard_rows_29();
std::span<const ::session_oracle::wire::Row> shard_rows_30();
std::span<const ::session_oracle::wire::Row> shard_rows_31();
std::span<const ::session_oracle::wire::Row> shard_rows_32();
std::span<const ::session_oracle::wire::Row> shard_rows_33();
std::span<const ::session_oracle::wire::Row> shard_rows_34();
std::span<const ::session_oracle::wire::Row> shard_rows_35();
std::span<const ::session_oracle::wire::Row> shard_rows_36();

std::span<const ::session_oracle::wire::Row> shard_rows_18() { return rows; }

}  // namespace session_oracle::fixy_wire
